Create board binary representation
marmelab/Hex pull request #88
Opened 2022-03-08 16:01 UTC by slax57

## Content

- [x] Add function to convert an array representation of the board to a binary one
- [x] Add function to do the opposite conversion

Related to: https://trello.com/c/eOslB09A/77-1-as-norbert-i-want-a-more-intelligent-ai

2022-03-08 16:44 UTC, fzaninotto requested changes
I'm not sure your optimization is an optimization. I advise you benchmark the 2 algos (e.g. by creating a random 19x19 board, and converting it 1000 times to binary)

2022-03-08 16:44 UTC, fzaninotto commented on web-app/src/common/utils.ts
> +            ? Math.pow(2, boardSize - 1 - (y * row.length + x))
very inefficient. Can't you do that with binary operators?

2022-03-08 16:44 UTC, fzaninotto commented on web-app/src/common/utils.ts
> +      prevRow +
can't you replace a `+` by a boolean `or`?

2022-03-08 16:44 UTC, fzaninotto commented on web-app/src/common/utils.ts
> +  const boardSize = board.length * board[0].length;
I don't understand why the boardsize is the total number of hex rather than the width. It forces you to do sqrt later...

2022-03-08 16:44 UTC, fzaninotto commented on web-app/src/common/utils.ts
> +      const filter: number = Math.pow(
same, try to do the same with no math operators, otherwise it's super slow

2022-03-09 10:01 UTC, atilbian commented on web-app/src/common/utils.spec.ts
> +    // when
Didn't I win the discussion about these comments :p ?

2022-03-09 10:01 UTC, atilbian commented on web-app/src/common/utils.ts
> +  board: Array<Array<Cell>>,
I think we can use a type here !

2022-03-09 10:01 UTC, atilbian commented on web-app/src/common/utils.ts
> +  boardSize: number;
I prefer recalculating it instead of having a redundant value ! I think it's not so much because it's done only one time per conversion.

2022-03-09 10:25 UTC, atilbian commented on web-app/src/common/utils.ts
> +  boardSize: number;
Ok as discussed in private this field is required so i close this comment.

2022-03-09 13:50 UTC, slax57 commented on web-app/src/common/utils.spec.ts
> +    // when
Sorry about that. Copy pasted `gameState.spec.ts` and forgot to remove them later 👼

2022-03-09 13:53 UTC, atilbian commented
> I'm not sure your optimization is an optimization. I advise you benchmark the 2 algos (e.g. by creating a random 19x19 board, and converting it 1000 times to binary)

2022-03-09 13:56 UTC, merged